version: '3'
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    image: postgresql
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: training
    container_name: postgres-container

volumes:
  pgdata: